---
title: "Daily and subdaily correlations"
author: "CTW"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, warning = F, echo = F}
knitr::opts_chunk$set(echo = FALSE, message = F, include = F, warning = F, fig.width = 8, fig.height = 8)  # don't display code by default
# load needed libraries
library(tidyverse)
library(lubridate)
library(readxl)
library(corrplot)
library(gplots)
library(sf)

# ctw functions to fetch climate datasets from EDI
source("~/github/nwt-data-munging/nwt_climate/R/fetch_data_functions.R")

# ctw personal prefs for environemnt and display
options(stringsAsFactors = F)
theme_set(theme_bw())

# specify datpath to temp synth folder on local drive
# > has unpublished pika data and simple features of all sites for temp synth with coords and elevation
datpath <- "/Users/scarlet/Documents/nwt_lter/temp_synth/"
# list of preppred data
datfiles <- list.files(paste0(datpath, "output/dat"), full.names = T)
```

```{r get ppt dats, eval = F}

# to check if snowfall reason for temp diffs in winterish months
#d1ppt <- getTabular()
```




```{r read in subdaily temps}

# need climate logger dat.. use the jennings data because it's infilled (only thru 2019) and semi-quality controlled (not QAQC after 2013, but done 1990-2013)
jennings <- getTabular(168)
sdl_hrly <- getTabular(57)

```


```{r get pika data}

pika_demo_edicg <- readRDS(datfiles[grepl("edi", datfiles)])
pika_demo_glv <- readRDS(datfiles[grepl("glv", datfiles)])
pika_demo_wk <- readRDS(datfiles[grepl("wkpika", datfiles)])
pika_habocc <- readRDS(datfiles[grepl("habocc", datfiles)])

```


```{r newest demography sites}
newdemoT <- read_excel(paste0(datpath, "unpublished_data/TalusTemperatureMetadataNWT2023-4Caitlin.xlsx"),trim_ws = T, skip = 3)

newdemoT_sites <- subset(newdemoT, select = c(DeploymentID, UTM_E, UTM_N, DateInSitu,DateEnd)) %>%
  data.frame()
```


```{r}
blacksand <- getTabular(238)
bs_llocs <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nwt.238.4&entityid=024605e81d0308609981d83268388934")

# subset to just control plots
bs_control <- subset(blacksand, grepl("con", local_site))
```



```{r aquatic data, echo=FALSE}

# I think just GL4 buoy and hobo loggers at inlet and outlet have continuous temp data
gl4_inout <- getTabular(259)
gl4b <- getTabular(188) # 2018-present

```

```{r create temporal coverage lut, include = F}
# track start-end dates for each sensor or dataset to use in clustering
# > i.e., 

# climate data
jennings_dates <- mutate(jennings, met = "airtemp_avg") %>%
  group_by(local_site, met) %>%
  summarise(start = min(date[!is.na(airtemp_avg)]),
            stop = max(date[!is.na(airtemp_avg)])) %>%
  ungroup()
sdl_hrly_dates <- sdl_hrly %>%
  subset(select = !grepl("flag", names(.))) %>%
  subset(select = grepl("local|airtemp.*_avg|soiltemp.*avg|date_time", names(.))) %>%
  gather(met, val, grep("temp", names(.))) %>%
  group_by(local_site, met) %>%
  summarise(start = as.Date(min(date_time_start[!is.na(val)])),
            stop = as.Date(max(date_time_start[!is.na(val)]))) %>%
  ungroup()

# gl4 aq data
gl4_inout_dates <- group_by(gl4_inout, local_site) %>%
  subset(!is.na(local_site)) %>%
  summarise(start = as.Date(min(timestamp[!is.na(temperature)])),
            stop = as.Date(max(timestamp[!is.na(temperature)]))) %>%
  ungroup() %>%
  mutate(met = paste(local_site, "temp"))

gl4b_dates <- group_by(gl4b, depth) %>%
  summarise(start = as.Date(min(timestamp[!is.na(temperature)])),
            stop = as.Date(max(timestamp[!is.na(temperature)]))) %>%
  ungroup() %>%
  mutate(local_site = "GL4 buoy",
         met = paste("temp", depth))

# pika sensors/placements
pika_demo_edicg_dates <- group_by(pika_demo_edicg, site, deployment_id, depth) %>%
  summarise(start = as.Date(min(date_time[!is.na(temperature)])),
            stop = as.Date(max(date_time[!is.na(temperature)]))) %>%
  ungroup()

pika_demo_glv_dates <- group_by(pika_demo_glv, site, datalogger) %>%
  summarise(start = as.Date(min(clean_date_time[!is.na(temp_c)])),
            stop = as.Date(max(clean_date_time[!is.na(temp_c)]))) %>%
  ungroup()

# not all wk sites have timestamps (hour of day)
pika_demo_wk_dates <- group_by(pika_demo_wk, site, datalogger) %>%
  summarise(start = as.Date(min(date[!is.na(temp_c)])),
            stop = as.Date(max(date[!is.na(temp_c)]))) %>%
  ungroup()

# pika occupancy
pika_habocc_dates <- group_by(pika_habocc, lut_plot) %>%
  summarise(start = as.Date(min(date_time[!is.na(temperature)])),
            stop = as.Date(max(date_time[!is.na(temperature)]))) %>%
  ungroup() %>%
  rename(site = lut_plot)

# stack pika dates
pika_alldates <- subset(pika_demo_edicg_dates, select = -depth) %>%
  rename(datalogger = deployment_id) %>%
  rbind(pika_demo_glv_dates) %>%
  rbind(pika_demo_wk_dates) %>%
  rbind(mutate(pika_habocc_dates, datalogger = site)[names(.)]) %>%
  rename(SITECOD = datalogger)

# black sand
bs_control_dates <- bs_control %>%
  subset(select = !grepl("flag", names(.))) %>%
  subset(select = grepl("local|date|soiltemp", names(.))) %>%
  gather(met, temp_c, grep("temp", names(.))) %>%
  group_by(local_site, met) %>%
  summarise(start = as.Date(min(date[!is.na(temp_c)])),
            stop = as.Date(max(date[!is.na(temp_c)]))) %>%
  ungroup()

# stack all times
timestable <- rbind(jennings_dates, sdl_hrly_dates) %>%
  rbind(
    rbind(gl4_inout_dates[names(.)], gl4b_dates[names(.)], bs_control_dates[names(.)])
    )
    
```


```{r fetch site info}
# sf prepped by ctw with all sites from nwt lter shapefile (on NWT website) and other sites (unpublished data or not included in nwt lter)
tempsynth_sites <- readRDS(paste0(datpath, "output/dat/tempsynth_allsites_sf.rdata"))
# keep only sites of interest for sub-daily comparison
tempsynth_sites <- subset(tempsynth_sites, !grepl("ARU|PTQ", SITECOD) & !grepl("Kelly|Nel", PI)) %>%
  # drop experimental sand plot
  subset(!grepl("_Sand_", SITECOD)) %>%
  # remove GL4 met sites
  subset(!(grepl("Mark", PI) & site == "GL4")) %>%
  mutate(site = gsub("WestKnoll", "West Knoll", site),
         site = gsub("GreenLakesValley", "Green Lakes Valley", site))

# join start-stop to each
pika_tempsynth <- left_join(pika_alldates, data.frame(tempsynth_sites))
# assign cable gate
pika_tempsynth_missing <- subset(pika_tempsynth, is.na(easting), select = c(site:stop)) %>%
  mutate(site2 = site,
         site2 = recode(site2, WK = "West Knoll", LL = "Long Lake", ML = "Mitchell Lake")) %>%
  left_join(subset(tempsynth_sites, select = -site), by = c("site2" = "SITECOD")) %>%
  subset(!site == "TBD", select = names(pika_tempsynth))
pika_tempsynth <- subset(pika_tempsynth, !is.na(easting)) %>%
  rbind(pika_tempsynth_missing)

# environmental sites not black sand
env_tempsynth <- subset(timestable, !grepl("_con", local_site)) %>%
  mutate(site = ifelse(grepl("d1|c1", local_site), casefold(local_site, upper = T),
                                      ifelse(grepl("gl4", local_site, ignore.case = T), "GL4",
                                             ifelse(local_site == "sdl", "SAD", NA)))) %>%
  mutate(SITECOD = ifelse(grepl("d1|c1|sdl", local_site, ignore.case = T), paste0(site, "-SSCREEN"),
                          ifelse(grepl("inle", local_site), "GL4 hobo inlet",
                                 ifelse(grepl("outl", local_site), "GL4 hobo outlet", "GL4 buoy"
                          )))) %>%
  left_join(data.frame(tempsynth_sites)) %>%
  mutate(SITECOD = ifelse(SITECOD == "GL4 buoy", paste(SITECOD, met), SITECOD)) %>%
  # drop hmp2 and 3 bc 1 reps both, and drop sdl avg airtemp with more recent start date since keith's covers that period
  subset(!(site == "SAD" & grepl("hmp[2-3]", met)) &!(site == "SAD" & year(start) == 2009)) %>%
  mutate(SITECOD = ifelse(grepl("hmp", met), paste(SITECOD, "hmp_airtemp"), SITECOD))


bs_tempsynth <- subset(timestable, grepl("_con", local_site))
bs_tempsynth$site <- "Audubon"
bs_tempsynth$site[grepl("l_", bs_tempsynth$local_site)] <- "Lefty"
bs_tempsynth$site[grepl("ek_", bs_tempsynth$local_site)] <- "EastKnoll"
bs_tempsynth$site[grepl("s_", bs_tempsynth$local_site)] <- "Soddie"
bs_tempsynth$site[grepl("t_", bs_tempsynth$local_site)] <- "Trough"
bs_tempsynth$sensor <- str_extract(bs_tempsynth$met, "(?<=soiltemp)[:digit:]")
bs_tempsynth$sensor <- with(bs_tempsynth, paste0(site, "-con-sen", sensor))

# create utms for sensors in black sand exp
bs_llocs_utms <- sf::st_as_sf(bs_llocs, coords = c("longitude", "latitude"))
st_crs(bs_llocs_utms) <- st_crs(tempsynth_sites)
bs_llocs_utms <- st_transform(bs_llocs_utms, crs = "EPSG:26913")
bs_llocs <- cbind(subset(bs_llocs, select = c(sensor:elevation)), st_coordinates(bs_llocs_utms))
names(bs_llocs)[names(bs_llocs) %in% c("X", "Y")] <- c("easting", "northing")

# join utms to bs_tempsynth
bs_tempsynth <- left_join(bs_tempsynth, bs_llocs)
bs_tempsynth <- rename(bs_tempsynth, lat = latitude, lon = longitude, elev_m = elevation, SITECOD = sensor)

# stack all and try clustering by lat, elevation, and start-stop
stack_timestable <- subset(bs_tempsynth, select = c(names(tempsynth_sites)[!grepl("proj|site|geom|PI|insitu", names(tempsynth_sites))], "start", "stop")) %>%
  rbind(env_tempsynth[names(.)]) %>%
  rbind(pika_tempsynth[names(.)]) %>%
  mutate(dups = duplicated(SITECOD)) %>%  #NWT-121 is duplicated (has different coords, relocated?). remove 2nd instance for now
  subset(!dups, select = -c(dups)) %>%
  # add next line after try with all dates
  subset(year(stop) >= 2018) %>%
  # add sensor nodes
  rbind(data.frame(mutate(tempsynth_sites[grepl("SN_",tempsynth_sites$SITECOD),],
                          start = as.Date("2018-08-01"),
                          stop = as.Date("2022-08-01")
                          ))[names(.)]
        )

# make wide format for correlations
stack_timestable_wide <- data.frame(stack_timestable) %>%   
  gather(met, val, 2:ncol(.)) %>%
  spread(SITECOD, val)
rownames(stack_timestable_wide) <- stack_timestable_wide$met
stack_timestable_wide <- stack_timestable_wide[names(stack_timestable_wide) != "met"]

heatmap.2(cor(stack_timestable_wide[rownames(stack_timestable_wide) %in% c("northing", "elev_m"),]), trace = "none", revC = T) #"start", "stop"

sites_hclust_time <- hclust(as.dist(1-(cor(stack_timestable_wide[rownames(stack_timestable_wide) %in% c("northing", "easting", "elev_m", "stop"),]))))
sites_dendro_time <- as.dendrogram(sites_hclust_time)
plot(sites_hclust_time, cex = 0.5)
plot(sites_dendro_time, type = "rectangle", cex = 0.25, ylim = c(0,0.000000005))

sites_cut_time <- data.frame(cluster = cutree(sites_hclust_time, k = 15))
sites_cut_time$SITECOD <- rownames(sites_cut_time) # i don't think that worked out very well.. need to have all years accounted for for better pairing (e.g., year binary var for whether data present or not that year)

# join site info back to plot
stack_timestable_clusters <- left_join(stack_timestable, sites_cut_time) %>%
  mutate(project = ifelse(grepl("SN_", SITECOD), "Sensor network",
                          ifelse(grepl("NWT-", SITECOD), "Pika occupancy study",
                                 ifelse(grepl("-con", SITECOD), "Black sand",
                                        ifelse(grepl("GL4", SITECOD), "GL4 monitoring",
                                               ifelse(grepl("d1|sdl|SAD|c1", SITECOD, ignore.case = T), "Climate monitoring", "Pika demography study"))
                          )))
         )

ggplot(stack_timestable_clusters, aes(easting, northing, col = factor(cluster))) +
  geom_text(aes(label = cluster), alpha = 0.5) +
  facet_wrap(~project)
# look for things that paired with climate stations, black sand, gl4, or sensors
ggplot(subset(stack_timestable_clusters, cluster %in% cluster[grepl("climate|black|sensor|gl4", project, ignore.case = T)]), aes(easting, northing, col = factor(cluster))) +
 geom_text(aes(label = cluster), alpha = 0.75) +
  facet_wrap(~project)

ggplot(stack_timestable_clusters, aes(easting, northing, col = project)) +
  geom_point(alpha = 0.5) +
  facet_wrap(~cluster)

ggplot(subset(stack_timestable_clusters, cluster %in% cluster[grepl("climate|black|sensor|gl4", project, ignore.case = T)]), aes(easting, northing, col = project)) +
  geom_point(alpha = 0.5) +
  geom_point(data = newdemoT_sites, aes(UTM_E, UTM_N), col = "black") +
 #geom_text(aes(label = cluster), alpha = 0.75) +
  facet_wrap(~cluster)

ggplot(subset(stack_timestable_clusters, cluster %in% c(3,4,7)), aes(easting, northing, col = project)) +
  geom_point(alpha = 0.5) +
  geom_text(data = newdemoT, aes(UTM_E, UTM_N, label = SensorID), size = 2, col = "black") +
 #geom_text(aes(label = cluster), alpha = 0.75) +
  facet_wrap(~cluster)

ggplot(subset(stack_timestable_clusters, cluster %in% c(7)), aes(easting, northing, col = project)) +
  geom_point(alpha = 0.5) +
  geom_point(data = newdemoT, aes(UTM_E, UTM_N, label = SensorID), alpha = 0.5, col = "black") +
  ggrepel::geom_text_repel(data = newdemoT, aes(UTM_E, UTM_N, label = SensorID), size = 3, col = "black") +
  ggrepel::geom_text_repel(aes(label = SITECOD), alpha = 0.5) +
 #geom_text(aes(label = cluster), alpha = 0.75) +
  facet_wrap(~cluster)

# try it subsetting sites to when buoy active
activebuoy <- stack_timestable %>%
  subset(year(stop) >= 2018)


# create wide matrix for spatial clustering
sites_wide <- data.frame(tempsynth_sites) %>%
  subset(select = c(SITECOD, easting, northing, elev_m)) %>%
  mutate(dups = duplicated(SITECOD)) %>%  #NWT-121 is duplicated (has different coords, relocated?). remove 2nd instance for now
  subset(!dups, select = -c(dups)) %>%
  mutate_at(names(.)[names(.) != "SITECOD"], as.numeric) %>%
  gather(met, val, 2:ncol(.)) %>%
  spread(SITECOD, val)

rownames(sites_wide) <- sites_wide$met
sites_wide <- sites_wide[names(sites_wide) != "met"]

# see what site associate based on x,y coords
heatmap.2(cor(sites_wide, use = "pairwise.complete.obs"), revC = T, trace = "none")

sites_hclust <- hclust(as.dist(1-(cor(sites_wide))))
sites_dendro <- as.dendrogram(sites_hclust)
plot(sites_hclust, cex = 0.5)
plot(sites_dendro, type = "rectangle", cex = 0.25, ylim = c(0,0.000000005))

sites_cut <- data.frame(cluster = cutree(sites_hclust, h = 0.000000005))
sites_cut$SITECOD <- rownames(sites_cut)
sites_sf_clusters <- left_join(data.frame(tempsynth_sites), sites_cut, by = "SITECOD") %>%
  subset(!is.na(cluster)) %>%
  sf::st_as_sf()

ggplot(sites_sf_clusters) +
  geom_sf(aes(color = factor(cluster), shape = PI), alpha = 0.75, size = 2) +
  labs(title = "Site clusters based on geocoords, elevation")

ggplot(sites_sf_clusters) +
  geom_sf(aes(color = elev_m, shape = PI), alpha = 0.75) +
  scale_color_viridis_c() +
  facet_wrap(~cluster)

ggplot(subset(sites_sf_clusters, cluster %in% cluster[grepl("SAD|GL4|D1", SITECOD)])) +
  geom_sf(aes(color = PI)) +
  geom_sf_text(aes(label = SITECOD, col = PI)) +
  facet_wrap(~cluster)

ggplot(sites_sf_clusters) +
  geom_point(aes(easting, northing, color = factor(cluster))) +
  ggrepel::geom_text_repel(aes(easting, northing,label = SITECOD, color = factor(cluster)), max.overlaps = 15)
  
ggplot(subset(sites_sf_clusters, cluster %in% cluster[grepl("SAD|GL4|D1", SITECOD)])) +
  geom_point(aes(easting, northing, color = factor(PI))) +
  ggrepel::geom_text_repel(aes(easting, northing,label = SITECOD, color = factor(PI)), max.overlaps = 15) +
  facet_wrap(~cluster)

ggplot(subset(sites_sf_clusters, cluster %in% cluster[grepl("SN_|D1", SITECOD)])) +
  geom_point(aes(easting, northing, size = elev_m, color = factor(PI)), alpha = 0.6) +
  ggrepel::geom_text_repel(aes(easting, northing,label = SITECOD), max.overlaps = 15) +
  facet_wrap(~cluster)

subset(sites_sf_clusters, cluster %in% cluster[grepl("West|Tvan", site)]) %>%
  mutate(project = gsub("Demography", "demography study", project),
         project = ifelse(grepl("Wireless", project), "Sensor node array", project)) %>%
ggplot() +
  geom_point(aes(easting, northing, size = elev_m, color = project), alpha = 0.6) +
  ggrepel::geom_text_repel(aes(easting, northing,label = SITECOD), max.overlaps = 20) +
  facet_wrap(~cluster)

subset(sites_sf_clusters, cluster %in% cluster[grepl("Green", site)]) %>%
  mutate(project = gsub("Demography", "demography study", project),
         project = ifelse(grepl("Wireless", project), "Sensor node array", project)) %>%
ggplot() +
  geom_point(aes(easting, northing, size = elev_m, color = project), alpha = 0.6) +
  ggrepel::geom_text_repel(aes(easting, northing,label = SITECOD), max.overlaps = 20) +
  facet_wrap(~cluster)
# 
```

```{r sensor node}
# package is knb-lter-nwt.210, each node has its own link
sn01 <- getTabular(210)

sn11 <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-nwt.210.6&entityid=169a6714085ee69b8ecae9d7bfd2399a")

# check ranges and structure
summary(sn11)
glimpse(sn11)
# see how correlated variables are just for one month

test <- sn11 %>%
  mutate(mon = month(date),
       yr = year(date),
       dy = day(date)) %>%
  subset(yr == 2017, select = -c(grep("flag|site|sensorno|date|yr|dy$|mon$|batt|snow|dts", names(.)))) #%>%
sn11cor <- cor.mtest(test)
corrplot(cor(test, use = "pairwise.complete.obs"),
         sig.level = 0.01,
         p.mat = sn11cor$p)
```


```{r test pairing}

# plot NWT-058 with D1
nwt058 <- subset(pika_habocc, grepl("58|73", plotnum)) %>%
  mutate(yr = year(date_time),
         mon = month(date_time),
         dt = date(date_time))
# plot sep 2017 (complete month)
ggplot(subset(nwt058, mon == 9 & yr == 2017), aes(date_time, temperature, col = plot)) +
  geom_line(data = subset(jennings, year == 2017 & local_site == "d1" & month(date) == 9), aes(`date-time`, airtemp_avg), col = "grey20") +
  geom_line() +
  scale_x_datetime(date_labels = "%b %d %Y") +
  labs(title = "Subdaily example: D1 hourly (black) infilled temp with NWT-053 and NWT-073")
  
```

```{r sn 1 with nwt 056}

unpub056 <- subset(unpub_pikaocc_temp, grepl("56|140", plot)) %>%
  mutate(date_time = as.POSIXct(date_time, format = "%Y-%m-%d %H:%M"))
nwt056 <- subset(pika_habocc, grepl("56|140", plotnum)) %>%
  #rbind(unpub056) %>%
  arrange(plot, date_time) %>%
  mutate(yr = year(date_time),
         mon = month(date_time),
         dt = date(date_time),
         plot = parse_number(plot),
         plot = gsub("-", "", plot))


sn01pair <- subset(sn01) %>%
  # na anything sub -40
  mutate(airtemp_avg = ifelse(airtemp_avg < -40, NA, airtemp_avg)) %>%
  mutate(yr = year(date),
         mon = month(date),
         dt = date(date)) %>%
  # subset to dates in nw056
  subset(dt <= max(nwt056$dt, na.rm = T))

ggplot(subset(nwt056, dt >= min(sn01pair$dt) & yr == 2019), aes(date_time, temperature, col = plot)) +
  # plot with sdl since close
  geom_line(data = mutate(subset(jennings, local_site == "sdl" & date %in% sn01pair$dt), dt = date), aes(`date-time`, airtemp_avg), col = "blue", alpha = 0.5) +
  geom_line(data = subset(sn01pair, yr == 2019), aes(date, airtemp_avg), col = "purple", alpha = 0.5) +
  geom_line(data = subset(sn01pair, yr == 2019), aes(date, soiltemp_5cm_avg), col = "grey60", alpha = 0.7) +
  geom_line(data = subset(sn01pair, yr == 2019), aes(date, soiltemp_30cm_avg), col = "black", alpha = 0.7) +
  geom_line() +
  scale_x_datetime(date_breaks = "1 week", date_labels = "%m-%d") +
  facet_wrap(~month(dt), scales = "free") +
  theme(axis.text.x = element_text(angle = 90))

ggplot(subset(nwt056, dt >= min(sn01pair$dt) & yr == 2020), aes(date_time, temperature, col = plot)) +
  # with sensor node 1
  geom_line(data = subset(sn01pair, yr == 2020), aes(date, airtemp_avg), col = "purple", alpha = 0.5) +
  geom_line(data = subset(sn01pair, yr == 2020), aes(date, soiltemp_5cm_avg), col = "grey60", alpha = 0.7) +
  geom_line(data = subset(sn01pair, yr == 2020), aes(date, soiltemp_30cm_avg), col = "black", alpha = 0.7) +
  geom_line() +
  scale_x_datetime(date_breaks = "1 week", date_labels = "%m-%d") +
  facet_wrap(~month(dt), scales = "free") +
  theme(axis.text.x = element_text(angle = 90))

# zoom in on jul and aug
ggplot(subset(nwt056, mon %in% c(7,8) & yr == 2020), aes(date_time, temperature)) +
  # with sensor node 1
  geom_line(data = subset(sn01pair, mon %in% c(7,8) & yr == 2020), aes(date, airtemp_avg), col = "purple", linewidth = 1, alpha = 0.5) +
  geom_line(data = subset(sn01pair, mon %in% c(7,8) & yr == 2020), aes(date, soiltemp_5cm_avg), col = "grey40", alpha = 0.7) +
  geom_line(data = subset(sn01pair, mon %in% c(7,8) & yr == 2020), aes(date, soiltemp_30cm_avg), col = "blue", alpha = 0.7) +
  geom_line() +
  #scale_x_datetime(date_breaks = "1 week", date_labels = "%m-%d") +
  theme_test() +
  facet_wrap(~plot + month(dt), nrow = 2, scales = "free") +
  theme(axis.text.x = element_text(angle = 90))

# just july
ggplot(subset(nwt056, mon ==7 & yr == 2020), aes(date_time, temperature)) +
  # with sensor node 1
  geom_line(data = subset(sn01pair, mon ==7  & yr == 2020), aes(date, airtemp_avg), col = "purple", linewidth = 1, alpha = 0.5) +
  geom_line(data = subset(sn01pair, mon ==7  & yr == 2020), aes(date, soiltemp_5cm_avg), col = "red", alpha = 0.7) +
  geom_line(data = subset(sn01pair, mon ==7  & yr == 2020), aes(date, soiltemp_30cm_avg), col = "blue", alpha = 0.7) +
  geom_line() +
  #scale_x_datetime(date_breaks = "1 week", date_labels = "%m-%d") +
  theme_test() +
  facet_wrap(~plot + month(dt), nrow = 2, scales = "free") +
  theme(axis.text.x = element_text(angle = 90))
```

